<a href="https://colab.research.google.com/github/dohyeonYoon/python-review/blob/main/Type_and_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1강 타입, 라이브러리 복습!!!!!!!!

**1.1 타입**

In [ ]:
print("dohyeon Yoon!")

dohyeon Yoon!


1.1.1 정수형(int)


In [ ]:
a = 1
b = 0
c= -1 

In [ ]:
print(a, type(a))
print(b, type(b))
print(c, type(c))

1 <class 'int'>
0 <class 'int'>
-1 <class 'int'>


In [ ]:
d= a+b 
print(d)

1


1.1.2 실수형(float)

In [ ]:
a= 1.2
b= 2.4
c= 0.

In [ ]:
#부동소수점 문제 
print(a+b)

3.5999999999999996


In [ ]:
print(a, type(a))
print(b, type(b))
print(c, type(c))

1.2 <class 'float'>
2.4 <class 'float'>
0.0 <class 'float'>


1.1.3 문자형(str) 

In [ ]:
#문자형 string
a= 'deep '
b= 'learning'
print(type(a),type(b))

<class 'str'> <class 'str'>


In [ ]:
print(a+b)

deep learning


1.1.4 T or F (bool) 

In [ ]:
a= True 
b= False
print(type(a), type(b))

<class 'bool'> <class 'bool'>


1.1.5 주의점

In [ ]:
#숫자형 문자 
a= 1
b= '1'
print(a)
print(b)
print(type(a), type(b))

1
1
<class 'int'> <class 'str'>


In [ ]:
c= int(b)
print(c, type(c))

1 <class 'int'>


1.1.6 리스트

In [ ]:
list1 = [1,2,3,4]
print(list1, type(list1))

[1, 2, 3, 4] <class 'list'>


In [ ]:
print(list1[0])
print(list1[2])
print(list1[:3])

1
3
[1, 2, 3]


1.1.7 튜플

In [ ]:
a= (1,2)
print(a, type(a))
print(a[0])
print(a[1])

(1, 2) <class 'tuple'>
1
2


In [ ]:
#튜플은 변경불가
a[1]= 100
print(a)

TypeError: ignored

In [ ]:
list1[1]=100
print(list1)

[1, 100, 3, 4]


1.1.8 딕셔너리

In [ ]:
a= {'class':['deep learning', 'machine learning'], 'student': [40,20] }
print(a)

{'class': ['deep learning', 'machine learning'], 'student': [40, 20]}


In [ ]:
print(type(a))

<class 'dict'>


In [ ]:
print(a['class'])

['deep learning', 'machine learning']


In [ ]:
print(a['student'])

[40, 20]


In [ ]:
print(a['student'][0])

40


1.1.9 Numpy 배열

In [ ]:
import numpy as np

arr= np.array([1,2,3,4])
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


**1.2 라이브러리**

In [ ]:
import numpy as np 
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
a= np.array([1,2,3,4])
b= np.ones(5)
c= np.zeros((5,2))

In [ ]:
print(a)
print(b)
print(c)

[1 2 3 4]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
