<a href="https://colab.research.google.com/github/dohyeonYoon/python-review/blob/main/For_and_While_loop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2강. 조건문, 반복문

# 2.1 조건문

In [ ]:
import numpy as np 

**2.1 조건문**

In [ ]:
x= 10

if x ==1: 
  print('x는 1이다')
else: 
  print('x는 1이 아니다')

x는 1이 아니다


In [ ]:
x= 10

if x == 1:
  print("x는 1입니다")
elif x ==2: 
  print("x는 2입니다")
elif x ==3:
  print("x는 3입니다")
else: 
  print("x는 1,2,3이 아닙니다")

x는 1,2,3이 아닙니다


#2.2 반복문

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
i=0
while i<5:
  print(i)
  i+=1

0
1
2
3
4


In [ ]:
f= np.random.randint(10,size=(10,3))
print(f)

[[5 5 4]
 [5 0 8]
 [9 2 0]
 [0 0 3]
 [0 4 3]
 [3 5 6]
 [8 3 9]
 [4 8 7]
 [7 4 9]
 [1 9 2]]


**2.3.2 break 문**

In [ ]:
pending =[1,3,5,3,8,1,4,5]


In [ ]:
# 짝수가 나오면 종료 
for i in pending:
  if i %2 ==0:
    print(i,'입니다.' )
    break

8 입니다.


**2.3.3 try-except문**

In [ ]:
x = [1,2,3,'s',4,5]

for i in x:
  y= i+1 
  print(y)

2
3
4


TypeError: ignored

In [ ]:
x= [1,2,3,'s',4,5]

for i in x:
  try: 
    y= i+1
    print(y)
  except:
    print(i, "는 오류입니다")

2
3
4
s 는 오류입니다
5
6
