# 2. 역전파 
인공 신경망을 최적화 하는 과정에서 미분은 필수적인 요소인데 파이토치는 최적화 과정인 역전파(backpropagation)를 쉽게 할 수 있도록 자동 미분 계산을 제공한다.

# 2.1 자동 미분 준비하기

In [10]:
import torch 

In [11]:
x= torch.ones(2,2, requires_grad=True) # x를 기준으로 미분할 수 있도록 해주는 함수
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [12]:
y= x+1 
z= 2*y**2 # 2(y^2)
res= z.mean()
print(y)
print(z)
print(res)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
tensor(8., grad_fn=<MeanBackward0>)


# 2.2 역전파

In [13]:
res.backward() # res를 기준으로 역전파를 진행한다.

# res= (z_1+z_2+z_3+z_4)/4
# z_i= 2 y_i **2
# z_i= 2(x_i+1)**2
# d(res)/dx_i = x_i +1 

In [14]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])
