# 1. 텐서

텐서(tensor)는 파이토치의 기본 단위이고 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하다

# 1.1 텐서 만들기

In [1]:
#라이브러리 불러오기 
import torch 
import numpy as np 

In [3]:
#빈 텐서 생성
x = torch.empty(5,4) #5x4 행렬 생성
print(x) #초기화 안해서 랜덤값 나타남

tensor([[-2.9405e-17,  3.0635e-41,  7.0065e-44,  6.8664e-44],
        [ 6.3058e-44,  6.7262e-44,  7.8473e-44,  6.3058e-44],
        [ 6.7262e-44,  7.0065e-44,  1.1771e-43,  6.7262e-44],
        [ 7.0065e-44,  8.1275e-44,  7.0065e-44,  7.4269e-44],
        [ 8.1275e-44,  6.8664e-44,  6.7262e-44,  6.4460e-44]])


In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.rand(5,6)

tensor([[0.1075, 0.7896, 0.1635, 0.8513, 0.1741, 0.4238],
        [0.4359, 0.6908, 0.3256, 0.7751, 0.9493, 0.2284],
        [0.4585, 0.6583, 0.2768, 0.7221, 0.4132, 0.8174],
        [0.9910, 0.2449, 0.6296, 0.5227, 0.8316, 0.1829],
        [0.8066, 0.3613, 0.5449, 0.7330, 0.8360, 0.3505]])

# 1.2 리스트, 넘파이 배열을 텐서로 만들기

In [7]:
l = [13,4] #리스트 생성
r= np.array([4,56,7]) #넘파이 배열 생성

In [8]:
torch.tensor(l)

tensor([13,  4])

In [9]:
torch.tensor(r)

tensor([ 4, 56,  7])

# 1.3 텐서의 크기와 타입 확인하기

In [15]:
x.size()[1] #텐서의 크기 

4

In [16]:
type(x) #텐서의 타입

torch.Tensor

# 1.4 텐서의 덧셈

In [17]:
x= torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)

tensor([[0.3167, 0.5485],
        [0.3182, 0.9783]])
tensor([[0.2360, 0.7474],
        [0.2885, 0.2951]])


In [18]:
x+y # 두 텐서의 합

tensor([[0.5527, 1.2960],
        [0.6067, 1.2734]])

In [19]:
torch.add(x,y) #두 텐서의 합 다른표현

tensor([[0.5527, 1.2960],
        [0.6067, 1.2734]])

In [20]:
y.add(x) # y에 x를 더한다

tensor([[0.5527, 1.2960],
        [0.6067, 1.2734]])

In [23]:
print("원래 y: ", y)
y.add_(x)
print("y= y+x: ", y)

원래 y:  tensor([[0.2360, 0.7474],
        [0.2885, 0.2951]])
y= y+x:  tensor([[0.5527, 1.2960],
        [0.6067, 1.2734]])


# 1.5 텐서의 크기 변환하기 

In [27]:
x= torch.rand(8,8)
print(x)

tensor([[0.3181, 0.7367, 0.3449, 0.4840, 0.6066, 0.1936, 0.2910, 0.7974],
        [0.5013, 0.9433, 0.6848, 0.3291, 0.3794, 0.7257, 0.2364, 0.5743],
        [0.7888, 0.2018, 0.5126, 0.8610, 0.0968, 0.2263, 0.2578, 0.7784],
        [0.4253, 0.7188, 0.5026, 0.4438, 0.2287, 0.5122, 0.8901, 0.8164],
        [0.3787, 0.8546, 0.6442, 0.8167, 0.9588, 0.0944, 0.4816, 0.9548],
        [0.0537, 0.8094, 0.3028, 0.6687, 0.5297, 0.4507, 0.0202, 0.8421],
        [0.9726, 0.9524, 0.8616, 0.3030, 0.7289, 0.2107, 0.0632, 0.2369],
        [0.4718, 0.9954, 0.2017, 0.6667, 0.6960, 0.0969, 0.9645, 0.4971]])


In [28]:
# x를 1차원으로 변환

a= x.view(64) #크기를 바꿔주는 view 8x8 = 64
print(a.size())

torch.Size([64])


In [32]:
# x를 3차원으로 변환

b= x.view(4,4,4) # -1 은 원래 크기가 되게 하는 값 8x8 > -1x4x4 즉, 4x4x4 
print(b.size())
print(b)

# -1은 원래 크기가 되게 하는 값이 자동으로 지정되기 떄문에 한 번만 사용할 수 있다.
# 예를들어 x.view(-1,-1,4)는 불가능  

torch.Size([4, 4, 4])
tensor([[[0.3181, 0.7367, 0.3449, 0.4840],
         [0.6066, 0.1936, 0.2910, 0.7974],
         [0.5013, 0.9433, 0.6848, 0.3291],
         [0.3794, 0.7257, 0.2364, 0.5743]],

        [[0.7888, 0.2018, 0.5126, 0.8610],
         [0.0968, 0.2263, 0.2578, 0.7784],
         [0.4253, 0.7188, 0.5026, 0.4438],
         [0.2287, 0.5122, 0.8901, 0.8164]],

        [[0.3787, 0.8546, 0.6442, 0.8167],
         [0.9588, 0.0944, 0.4816, 0.9548],
         [0.0537, 0.8094, 0.3028, 0.6687],
         [0.5297, 0.4507, 0.0202, 0.8421]],

        [[0.9726, 0.9524, 0.8616, 0.3030],
         [0.7289, 0.2107, 0.0632, 0.2369],
         [0.4718, 0.9954, 0.2017, 0.6667],
         [0.6960, 0.0969, 0.9645, 0.4971]]])


# 1.6 텐서에서 넘파이로 변환

In [33]:
x= torch.rand(8,8)
y= x.numpy()
print(y)

[[0.02986807 0.11982906 0.9230363  0.27256596 0.43994474 0.74138236
  0.06650531 0.10702199]
 [0.28041244 0.37050974 0.5603955  0.49992627 0.76727027 0.32239562
  0.65903217 0.74768937]
 [0.31897283 0.1195268  0.16617477 0.09310192 0.5743321  0.787471
  0.97576016 0.0162878 ]
 [0.7801761  0.73923934 0.6163887  0.8141799  0.2789927  0.79919946
  0.24985033 0.87209296]
 [0.64141357 0.55260646 0.50664115 0.10408896 0.4399596  0.9206607
  0.34381944 0.44673616]
 [0.02743047 0.9063133  0.81417775 0.94587755 0.27131772 0.07177413
  0.8860258  0.38366753]
 [0.4317482  0.9893289  0.560525   0.33350033 0.32033497 0.24632579
  0.7447061  0.863448  ]
 [0.24690038 0.20568705 0.7651674  0.34155    0.17679721 0.47800928
  0.13271731 0.48423636]]


In [34]:
type(y)

numpy.ndarray

# 1.7 단일 텐서에서 값으로 뽑아내기 

In [35]:
x= torch.ones(1)

In [37]:
print(x)
print(x.item()) # .item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

tensor([1.])
1.0
